events { worker_connections 1024; }

http {
    # Grup upstream server backend (VM 2 & VM 3)
    upstream backend_servers {
        server 20.6.129.82:5000;  # IP Public Backend 1
        server 20.2.140.143:5000; # IP Public Backend 2
    }

    server {
        listen 80;

        # 1. Jalur untuk API Gateway (Order Processing)
        location /order {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Jalur untuk Static Files Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}